### ISSUE TITLE
TraceId is missed in the log

### ISSUE THREAD

**Issue by vicbell** [Nike-Inc/cerberus-management-service#35] opened 2017-04-21 15:57 UTC
I say most of the endpoints in this project use `CompletableFuture.supplyAsync` when override the method 
`CompletableFuture<ResponseInfo<O>> 
execute(RequestInfo<I> request, Executor longRunningTaskExecutor,  ChannelHandlerContext ctx);`  
of `StandardEndpoint<I, O>`. 

I test it locally and find the `traceId` is missed in the log . I use
 `AsyncNettyHelper.supplierWithTracingAndMdc(
					() -> doExecute(request, longRunningTaskExecutor, ctx)
					, ctx)` 
then the traceId is printed normally.

Do you have the same problem?

**Comment by tlisonbee** [comment] 2017-05-09 18:43
Hi @vicbell, 

Yes, I see the same thing, traceId isn't showing up in our logs.  I'm guessing the traceId is related to the tracing features of Riposte which we haven't used and I'm not familiar with.  

Also, it looks like we are not on the latest version of Riposte, so I'm not sure if this is a known bug with the version we're on.  @nicmunroe may be able to shed light.

Can you say more about the context of this problem?  Was this in relation to your usage of Cerberus?  Or were you just encountering the same thing on another Riposte project?

Thanks.

**Comment by nicmunroe** [comment] 2017-05-10 05:21
@tlisonbee, the problem is that the automatic trace ID showing up in the logs depends on the tracing context following you when you hop threads (it's ThreadLocal-based because SLF4J MDC is ThreadLocal-based). Doing a `CompletableFuture.*Async(...)` causes the lambda to be executed on a different thread, so without doing anything extra the tracing context is lost and trace IDs won't show up in the logs for any logging done during the lambda. 

@vicbell is on the right track - rather than passing a basic lambda to the `CompletableFuture`, pass in a `AsyncNettyHelper.supplierWithTracingAndMdc(() -> /* original lambda code */)` instead. The `AsyncNettyHelper.*withTracingAndMdc(...)` are factory methods for creating lambdas where the tracing context will be propagated for you automatically when the lambda is executed.

So it should be a pretty straightforward refactor to find any place you're hopping threads (like `CompletableFuture.*Async(...)` calls) and wrap the logic in a `AsyncNettyHelper.*withTracingAndMdc(...)`. Let me know if there's any more questions on this.

**Comment by vicbell** [comment] 2017-05-10 12:34
@tlisonbee I am using Riposte, I want to find a best practice of how to use Reposte and i found Cerberus. TraceId is very usefull for tracing problems, i think it should not missing in logs.

@nicmunroe If i use `CompletableFuture.supplyAsync` for every endpoint (Just like Cerberus is doing so) in my project, Netty is using three kind of thread for every request boss thread-> worker thread -> business thead, will this be a performance problem（Because of the frequent thread context switching）?

**Comment by nicmunroe** [comment] 2017-05-11 19:38
@vicbell you are correct that it is best to avoid unnecessary thread context switching. The boss threads and worker threads are just how Netty works - there's no need to worry about them. You *do* have control over when and where you hop threads when executing an endpoint however, and that's where things get tricky. 

For maximum performance/throughput: if your endpoint's execution is "quick enough" then you should *not* do an async execution - you should just do your logic synchronously on the Netty worker thread you're on when the endpoint execution starts and return a `CompletableFuture.completedFuture(...)` at the end. If your endpoint has to wait for anything out-of-process (e.g. calling another microservice over HTTP, or calling a database), or if it will take "too long" then you should do the waiting or work asynchronously off the Netty worker thread. 

The problem is that there's no one-size-fits-all rule for what "quick enough" and "too long" mean. It depends on many factors and requires experimentation on your part to learn when synchronous execution is appropriate. I generally find that if an endpoint will *always* return in under 1-2 milliseconds assuming you have available CPU *and* there's nothing happening during your endpoint that requires waiting on some out-of-process thing to return (like HTTP or database calls) then synchronous execution might be best for maximum throughput (although you should run some load tests against your endpoints to confirm synchronous execution is better - don't just assume it). Simple payload processing and using in-memory caches to build responses are likely candidates.

And when you do have out-of-process things to wait on like HTTP or database calls, you can see if there's an async nonblocking driver that returns a `CompletableFuture` or equivalent future, and chain your endpoint logic on those to avoid extra thread context switching (again, only if your chaining endpoint logic is "quick enough").

So squeezing maximum performance can be tricky and difficult, and can take lots of experimentation and experience before you instinctively do the right thing the first time. Because it can be so tricky and easy to do the wrong thing, it's not a bad idea to just always farm out to a `CompletableFuture.*Async(...)` method and use the given `longRunningTaskExecutor` as the `CompletableFuture`'s executor. You may not get the *best* throughput that way, but it's safe and you should still get good throughput.

**Comment by tlisonbee** [comment] 2017-05-11 20:22
Fixed in version 0.18.3

**Closed by tlisonbee** 2017-05-11 20:22 UTC
